### ISSUE TITLE
Style on-hover/popup text

### ISSUE THREAD

**Issue by 2exp3** [Appsilon/rhino-showcase#5]
- [ ] Appsilon/rhino-showcase#9 
- [ ] Appsilon/rhino-showcase#11 
- [ ] Appsilon/rhino-showcase#10
